# Configuration for Zaino

# gRPC server config:

# Zainod's gRPC server listen address.
bind_address = "127.0.0.1:8137"

# Enables TLS for gRPC connections.
tls = false

# Path to the TLS certificate file in PEM format.
# Required if `tls` is true.
tls_cert_path = None

# Path to the TLS private key file in PEM format.
# Required if `tls` is true.
tls_key_path = None



# JsonPRC client config:

# Full node / validator listen port.
zebrad_port = 18232

# Optional full node / validator Username.
node_user = "xxxxxx"

# Optional full node / validator Password.
node_password = "xxxxxx"



# Mempool and Non-Finalised State and Finalised State config:

# Capacity of the Dashmaps used for the Mempool.
# Also use by the BlockCache::NonFinalisedState when using the FetchService.
#
# None by default.
map_capacity = None

# Number of shard used in the DashMap used for the Mempool.
# Also use by the BlockCache::NonFinalisedState when using the FetchService.
#
# shard_amount should greater than 0 and be a power of two.
# If a shard_amount which is not a power of two is provided, the function will panic.
#
# None by default.
map_shard_amount = None

# Block Cache database file path.
#
# This is Zaino's Compact Block Cache db if using the FetchService or Zebra's RocksDB if using the StateService.
#
# None by default, this defaults to `$HOME/.cache/zaino/`
db_path = None

# Block Cache database maximum size in gb.
#
# Only used by the FetchService.
#
# None by default
db_size = None



# Network:

# Network chain type (Mainnet, Testnet, Regtest).
network = "Testnet"



# Options:

# Disables internal sync and stops zaino waiting on server to sync with p2p network.
# Useful for testing.
no_sync = false

# Disables the FinalisedState in the BlockCache
#
# Only used by the FetchServic.
# Used for testing.
no_db = false

# Disables internal mempool and blockcache.
#
# For use by lightweight wallets that do not want to run any extra processes.
#
# NOTE: Currently unimplemented as will require either a Tonic backend or a JsonRPC server.
# no_state = false

